[[bin]]
name = 'offchain-node'
path = 'src/main.rs'

[package]
authors = ['Anonymous']
build = 'build.rs'
edition = '2018'
name = 'offchain-node'
version = '2.0.0'

[dependencies]
futures = "0.3.1"
log = "0.4.8"
tokio = "0.1.22"
parking_lot = "0.9.0"
trie-root = "0.15.2"
ctrlc = { version = "3.1.3", features = ["termination"] }
codec = { package = "parity-scale-codec", version = "1.0.0" }
futures01 = { package = "futures", version = "0.1" }

# substrate dependencies from github
[dependencies.aura]
git = "https://github.com/paritytech/substrate.git"
rev = "368318c9b11c07596cde5dc37220258cfa7dfa76"
package = "sc-consensus-aura"

[dependencies.sp-io]
git = "https://github.com/paritytech/substrate.git"
rev = "368318c9b11c07596cde5dc37220258cfa7dfa76"

[dependencies.sc-cli]
git = "https://github.com/paritytech/substrate.git"
rev = "368318c9b11c07596cde5dc37220258cfa7dfa76"

[dependencies.primitives]
git = "https://github.com/paritytech/substrate.git"
rev = "368318c9b11c07596cde5dc37220258cfa7dfa76"
package = "sp-core"

[dependencies.sc-executor]
git = "https://github.com/paritytech/substrate.git"
rev = "368318c9b11c07596cde5dc37220258cfa7dfa76"

[dependencies.sc-service]
git = "https://github.com/paritytech/substrate.git"
rev = "368318c9b11c07596cde5dc37220258cfa7dfa76"

[dependencies.inherents]
git = "https://github.com/paritytech/substrate.git"
rev = "368318c9b11c07596cde5dc37220258cfa7dfa76"
package = "sp-inherents"

[dependencies.txpool]
git = "https://github.com/paritytech/substrate.git"
rev = "368318c9b11c07596cde5dc37220258cfa7dfa76"
package = "sc-transaction-pool"

[dependencies.txpool-api]
git = "https://github.com/paritytech/substrate.git"
rev = "368318c9b11c07596cde5dc37220258cfa7dfa76"
package = "sp-transaction-pool-api"

[dependencies.network]
git = "https://github.com/paritytech/substrate.git"
rev = "368318c9b11c07596cde5dc37220258cfa7dfa76"
package = "sc-network"

[dependencies.aura-primitives]
git = "https://github.com/paritytech/substrate.git"
rev = "368318c9b11c07596cde5dc37220258cfa7dfa76"
package = "sp-consensus-aura"

[dependencies.consensus-common]
git = "https://github.com/paritytech/substrate.git"
rev = "368318c9b11c07596cde5dc37220258cfa7dfa76"
package = "sp-consensus"

[dependencies.grandpa]
git = "https://github.com/paritytech/substrate.git"
rev = "368318c9b11c07596cde5dc37220258cfa7dfa76"
package = "sc-finality-grandpa"

[dependencies.grandpa-primitives]
git = "https://github.com/paritytech/substrate.git"
rev = "368318c9b11c07596cde5dc37220258cfa7dfa76"
package = "sp-finality-granpda"

[dependencies.sc-client]
git = "https://github.com/paritytech/substrate.git"
rev = "368318c9b11c07596cde5dc37220258cfa7dfa76"

[dependencies.runtime]
package = "runtime"

[dependencies.sp-runtime]
git = "https://github.com/paritytech/substrate.git"
rev = "368318c9b11c07596cde5dc37220258cfa7dfa76"

[dependencies.basic-authorship]
git = "https://github.com/paritytech/substrate.git"
rev = "368318c9b11c07596cde5dc37220258cfa7dfa76"
package = "sc-basic-authority"

[build-dependencies]
vergen = "3.0.4"

[build-dependencies.build-script-utils]
git = "https://github.com/paritytech/substrate.git"
rev = "368318c9b11c07596cde5dc37220258cfa7dfa76"
package = "substrate-build-script-utils"
